# Generated by Django 5.0.4 on 2024-04-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_photo'),
        ('main_app', '0013_remove_order_quantity'),
    ]

    operations = [
    ]
