# Generated by Django 5.0.4 on 2024-04-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_order_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='pickup_person',
        ),
    ]
