# Generated by Django 5.0.4 on 2024-04-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_order_customer_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default='2024-04-23', verbose_name='Order Date'),
        ),
    ]
