# Generated by Django 5.0.4 on 2024-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_pickup_products_product_pickups_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
