# Generated by Django 5.0.4 on 2024-04-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.pickup'),
        ),
    ]
