# Generated by Django 5.0.4 on 2024-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='products',
            field=models.ManyToManyField(to='main_app.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='pickups',
            field=models.ManyToManyField(to='main_app.pickup'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default='2024-04-24', verbose_name='Order Date'),
        ),
    ]
